# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-08 08:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_online', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='optiondetail',
            name='question',
            field=models.TextField(default='sdfg'),
        ),
        migrations.AlterField(
            model_name='exam_details',
            name='totalTime',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='optiondetail',
            name='q_id',
            field=models.IntegerField(),
        ),
    ]
