# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-08 08:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_online', '0002_auto_20170408_0804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questiondetails',
            name='code',
            field=models.TextField(),
        ),
    ]
