# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-08 09:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_online', '0003_auto_20170408_0815'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questiondetails',
            name='correctAnswer',
        ),
        migrations.AddField(
            model_name='optiondetail',
            name='correctAnswer',
            field=models.TextField(default='t'),
        ),
        migrations.AlterField(
            model_name='optiondetail',
            name='question',
            field=models.TextField(),
        ),
    ]
