# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-08 10:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_online', '0004_auto_20170408_0931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scores',
            name='user',
        ),
        migrations.AlterField(
            model_name='scores',
            name='examCode',
            field=models.TextField(),
        ),
    ]
