# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-08 10:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_online', '0005_auto_20170408_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='scores',
            name='user',
            field=models.TextField(default='qwerty'),
        ),
    ]
