# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-08 17:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_online', '0007_auto_20170408_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam_details',
            name='totalTime',
            field=models.IntegerField(),
        ),
    ]
