# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-08 18:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_online', '0009_optiondetail_questionmark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optiondetail',
            name='questionMark',
            field=models.IntegerField(),
        ),
    ]
