# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-09 11:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam_online', '0012_auto_20170408_1836'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scores',
            name='rank',
        ),
    ]
