# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-09 17:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_online', '0013_remove_scores_rank'),
    ]

    operations = [
        migrations.CreateModel(
            name='timeManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.TextField()),
                ('startTime', models.TimeField(default=datetime.datetime(2017, 4, 9, 17, 58, 21, 898549))),
            ],
        ),
    ]
